name: Unit Test

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    branches:
      - master
  pull_request:
    # File paths to consider in the event. Optional; defaults to all.
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ut.yaml'

jobs:
  ut:
    name: UT on ubuntu-22.04
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependency
        run: |
          sudo apt update && sudo apt install -y cmake libopenblas-dev libaio-dev g++-12 gcc-12 python3 python3-pip \
          && pip3 install conan==1.61.0 \
          && conan remote add default-conan-local https://milvus01.jfrog.io/artifactory/api/conan/default-conan-local
      - name: Restore Conan Packages
        uses: actions/cache@v4
        with:
          path: ~/.conan
          key: milvus-common-ubuntu-22.04-${{ hashFiles('conanfile.py')}}
          restore-keys: milvus-common-ubuntu-22.04-
      - name: Build & Run
        run: |
          mkdir build && cd build && conan install .. --build=missing -o with_ut=True -s compiler.libcxx=libstdc++11 -s compiler.version=12 -s build_type=Release && conan build .. \
          && ./test/test_cachinglayer/cachinglayer_test && ./test/all_tests
      - name: Save Conan Packages
        uses: actions/cache/save@v4
        with:
          path: ~/.conan
          key: milvus-common-ubuntu-22.04-${{ hashFiles('conanfile.py')}}
          restore-keys: milvus-common-ubuntu-22.04-
